chore(deps): upgrade dependencies
Upgrades project dependencies. See details in [workflow run].

[Workflow Run]: https://github.com/cdklabs/cdk-nag/actions/runs/1639156312

------

*Automatically created by projen via the "upgrade-v2-main" workflow*

Signed-off-by: github-actions <github-actions@github.com>

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -29,49 +29,35 @@ jobs:
           git add .
 
           git diff --staged --patch --exit-code > .repo.patch || echo "::set-output name=self_mutation_happened::true"
-      - if: ${{ steps.self_mutation.outputs.self_mutation_happened }}
+      - if: steps.self_mutation.outputs.self_mutation_happened
         name: Upload patch
         uses: actions/upload-artifact@v2
         with:
           name: .repo.patch
           path: .repo.patch
+      - name: Fail build on mutation
+        if: steps.self_mutation.outputs.self_mutation_happened
+        run: >-
+          echo "::error::Files were changed during build (see build log). If
+          this was triggered from a fork, you will need to update your branch."
+
+          cat .repo.patch
+
+          exit 1
       - name: Upload artifact
         uses: actions/upload-artifact@v2.1.1
-        if: ${{ ! steps.self_mutation.outputs.self_mutation_happened }}
         with:
           name: build-artifact
           path: dist
     container:
       image: jsii/superchain:1-buster-slim-node14
-  anti-tamper:
-    needs: build
-    runs-on: ubuntu-latest
-    permissions: {}
-    if: ${{ needs.build.outputs.self_mutation_happened &&
-      github.event.pull_request.head.repo.full_name != github.repository }}
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v2
-        with:
-          ref: ${{ github.event.pull_request.head.ref }}
-          repository: ${{ github.event.pull_request.head.repo.full_name }}
-      - name: Download patch
-        uses: actions/download-artifact@v2
-        with:
-          name: .repo.patch
-          path: ${{ runner.temp }}
-      - name: Apply patch
-        run: '[ -s ${{ runner.temp }}/.repo.patch ] && git apply ${{ runner.temp
-          }}/.repo.patch || echo "Empty patch. Skipping."'
-      - name: Found diff after build (update your branch)
-        run: git add . && diff --staged --exit-code
   self-mutation:
     needs: build
     runs-on: ubuntu-latest
     permissions:
       contents: write
-    if: ${{ needs.build.outputs.self_mutation_happened &&
-      !(github.event.pull_request.head.repo.full_name != github.repository) }}
+    if: always() && needs.build.outputs.self_mutation_happened &&
+      !(github.event.pull_request.head.repo.full_name != github.repository)
     steps:
       - name: Checkout
         uses: actions/checkout@v2
@@ -100,7 +86,7 @@ jobs:
     needs: build
     runs-on: ubuntu-latest
     permissions: {}
-    if: ${{ ! needs.build.outputs.self_mutation_happened }}
+    if: "! needs.build.outputs.self_mutation_happened"
     steps:
       - uses: actions/setup-node@v2
         with:
@@ -122,7 +108,7 @@ jobs:
     needs: build
     runs-on: ubuntu-latest
     permissions: {}
-    if: ${{ ! needs.build.outputs.self_mutation_happened }}
+    if: "! needs.build.outputs.self_mutation_happened"
     steps:
       - uses: actions/setup-node@v2
         with:
